Script started on Mon 14 Mar 2016 07:30:47 AM CST
[1m[3m%[23m[1m[0m                                                                                ]2;kh@debian:~/lab1[0m[23m[24m[J[38;5;140mkh@debian[39m [38;5;110m~/lab1[39m $ [K[?1h=wwhw  wwhoami; pwd[?1l>
]2;kh@debian:~/lab1kh
/home/kh/lab1
[1m[3m%[23m[1m[0m                                                                                ]2;kh@debian:~/lab1[0m[23m[24m[J[38;5;140mkh@debian[39m [38;5;110m~/lab1[39m $ [K[?1h=ggit config -1 l[?1l>
]2;kh@debian:~/lab1user.name=KlareH
user.email=klare0216@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/klare0216/lab1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
[1m[3m%[23m[1m[0m                                                                                ]2;kh@debian:~/lab1[0m[23m[24m[J[38;5;140mkh@debian[39m [38;5;110m~/lab1[39m $ [K[?1h=ggit clone https://github.com/klare0216/lab1.git[?1l>
]2;kh@debian:~/lab1Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[1m[3m%[23m[1m[0m                                                                                ]2;kh@debian:~/lab1[0m[23m[24m[J[38;5;140mkh@debian[39m [38;5;110m~/lab1[39m $ [K[?1h=ccat lab.script1.script[1C[1C[1C[1C[1C[1C[1C[11D           [11D c  

Script done on Mon 14 Mar 2016 07:32:25 AM CST
