Script started on Mon 14 Mar 2016 11:19:20 AM CST
E64021012@2015cpp:~/Lion$ git config -l[Kgit config -l[2Pwhoami; pwdgit config --list [1@ [C[C[C[C[C[1P[C[C[C[C[C[7Pwhoami; pwd
E64021012
/home/E64021012/Lion
E64021012@2015cpp:~/Lion$ whoami; pwdgit config -l
use.name=klareH
use.email=klare0216@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/klare0216/lab1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
color.ui=true
E64021012@2015cpp:~/Lion$ git clone https://github.com/klare0216/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
E64021012@2015cpp:~/Lion$ exit

Script done on Mon 14 Mar 2016 11:20:27 AM CST
